CREATE TABLE User (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    FacebookID VARCHAR(255) UNIQUE NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    HashedPassword VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Address TEXT NULL,
    Description TEXT NULL,
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);