CREATE TABLE IF NOT EXISTS Carpools (
  CarpoolID INT PRIMARY KEY AUTO_INCREMENT,
  HostUserID INT NOT NULL,
  EventID INT NOT NULL,
  MaxSeats INT DEFAULT 5,
  AvailableSeats INT NOT NULL,
  Notes TEXT,
  Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (HostUserID) REFERENCES Users(UserID) ON DELETE CASCADE,
  FOREIGN KEY (EventID) REFERENCES Events(EventID) ON DELETE CASCADE
);