CREATE TABLE IF NOT EXISTS CarpoolRequests (
  RequestID INT PRIMARY KEY AUTO_INCREMENT,
  CarpoolID INT NOT NULL,
  UserID INT NOT NULL,
  Status ENUM('Pending', 'Accepted', 'Rejected') DEFAULT 'Pending',
  RequestedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (CarpoolID) REFERENCES Carpools(CarpoolID) ON DELETE CASCADE,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);